### ISSUE TITLE
command not supported error in sbt-vim.py

### ISSUE THREAD

**Issue by sathisz** [ktvoelker/sbt-vim#4]
```
Error detected while processing /home/sathish/.vim/plugged/sbt-vim/plugin/sbt.vim:
line   20:
E319: Sorry, the command is not available in this version: pyfile /home/sathish/.vim/plugged/sbt-vim/plugin/../python/sbt-vim.py
```
when I open file in file it shows the following error
I am using
Vim - 7.4
Python - 3.5
OS - Linux Mint
Vim package manager - Plug

**Comment by ktvoelker** [comment]
It sounds like your vim is not compiled with python support. You can check by running `vim --version` and looking for `+python` in the output.

**Comment by nkwsy** [comment]
I get the same error, I am assuming `+python3` is not enough.

**Comment by ktvoelker** [comment]
Yeah, the vim extensions for Python 2 and 3 are separate things. I don't have time to work on this but you are welcome to send a PR adding support for Python 3 (or even replacing 2 with 3). It should be pretty simple.

**Comment by sathisz** [comment]
Same error exists

**Comment by ktvoelker** [comment]
Then I guess your vim is still not compiled with Python 2 support.
